#!/bin/bash

###############################################################################
# bash_profile
###############################################################################

# Load shell dotfiles
source ${HOME}/.bash_profile.aliases
source ${HOME}/.bash_profile.aliases-dev
source ${HOME}/.bash_profile.intro
source ${HOME}/.bash_profile.prompt
source ${HOME}/.bash_profile.work

# Updates PATH for the Google Cloud SDK, installed via Homebrew.
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc'

# Enables shell command completion for Google Cloud SDK, installed via Homebrew.
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'

export PATH=$PATH:~/bin
export PATH="/usr/local/sbin:$PATH"

# Homebrew coreutils
export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH

# Yarn
export PATH="$PATH:$HOME/.yarn/bin"

# NVM - Node Version Manager
export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"

# Heroku CLI
export PATH="/usr/local/heroku/bin:$PATH"

# Set VSCode as a default editor
export EDITOR='code -w'

# Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

test -e ${HOME}/.iterm2_shell_integration.bash && source ${HOME}/.iterm2_shell_integration.bash


###############################################################################
# Everything below this comment was probably added by an application or
# package. To keep things organized, you should probably put them into
# your sourced config files above :)
###############################################################################
