#!/bin/bash

###############################################################################
# setup-apps
#
# A shell script to automate application setup on Mac OS X.
###############################################################################


###############################################################################
# Install fonts and applications with Homebrew cask
###############################################################################
echo "Homebrew: installing Homebrew Cask..."
# brew install caskroom/cask/brew-cask # install Cask
# brew tap caskroom/versions # install beta versions with Cask
# brew tap caskroom/fonts # install fonts with Cask


###############################################################################
# Install fonts with Homebrew Cask
###############################################################################
# echo "Homebrew Cask: installing fonts..."
# fonts=(
#   font-source-sans-pro
#   font-input
#   font-roboto
# )
# brew cask install ${fonts[@]}


###############################################################################
# Install applications with Homebrew Cask
###############################################################################
echo "Homebrew Cask: installing apps..."
brew cask install 1password
brew cask install adobe-creative-cloud
brew cask install alfred
brew cask install atom
brew cask install box-sync
brew cask install dash
brew cask install docker
# brew cask install dropbox
brew cask install firefox
brew cask install framer
brew cask install github-desktop
brew cask install gitter
brew cask install google-cloud-sdk
brew cask install google-chrome
brew cask install google-drive
brew cask install hyper
brew cask install imageoptim
brew cask install java
brew cask install obs
brew cask install omnidazzle
brew cask install paparazzi
brew cask install paw
brew cask install postman
brew cask install private-internet-access
brew cask install screaming-frog-seo-spider
brew cask install screenflow
brew cask install sketch
brew cask install sketch-toolbox
brew cask install skype
brew cask install slack
brew cask install sonos
brew cask install spectacle
brew cask install spotify
brew cask install sublime-text
brew cask install teamviewer
brew cask install toggldesktop
brew cask install transmit


###############################################################################
# Execute installers downloaded with Homebrew Cask
###############################################################################
echo "Opening installers..."

echo "Opening Installer: Adobe Creative Cloud"
open /usr/local/Caskroom/adobe-creative-cloud/latest/Creative\ Cloud\ Installer.app/

echo "Opening Installer: Private Internet Access"
open /usr/local/Caskroom/private-internet-access/latest/Private\ Internet\ Access\ Installer.app


###############################################################################
# Cleanup
###############################################################################
brew cask cleanup
echo "macOS Apps Done Setup!"
