#!/bin/zsh

###############################################################################
# setup-brew
#
# A shell script to automate system tool setup for Mac OS X.
###############################################################################


###############################################################################
# Install Xcode command line tools
###############################################################################
echo "Installing Xcode Command Line Tools..."
xcode-select --install


###############################################################################
# Check for Homebrew, else install
###############################################################################
echo "Checking for, or Installing Homebrew..."
if [ -z `command -v brew` ]; then
    echo "Brew is missing! Installing it..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi;


###############################################################################
# Make sure we're on latest Homebrew
###############################################################################
echo "Homebrew: updating..."
brew update


###############################################################################
# Upgrade any already-installed formulae
###############################################################################
echo "Homebrew: upgrading..."
brew upgrade

###############################################################################
# Tap Kegs
###############################################################################
echo "Homebrew: Tapping kegs..."
tap "adoptopenjdk/openjdk"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

###############################################################################
# Install utilities
###############################################################################
echo "Homebrew: updating unix tools..."
brew install zsh
brew install homebrew/cask-fonts/font-fira-mono-for-powerline

###############################################################################
# Setup NVM, NodeJS, and Yarn
###############################################################################
echo "Homebrew: setting up nvm..."
brew install nvm
nvm --version
nvm ls-remote
nvm install --lts
nvm ls
nvm use default

echo "Homebrew: setting up yarn..."
brew install yarn


###############################################################################
# Install binaries and other packages
###############################################################################
echo "Homebrew: installing binaries and other packages..."
brew install ruby
brew install ffmpeg
brew install git
brew install heroku/brew/heroku
brew install httpie
brew install imagemagick
brew install mackup
brew install mas
brew install nginx
brew install rename
brew install tree
brew install webkit2png
brew install automake
brew install coreutils
brew install gh
brew install sqlite
brew install pkg-config
brew install gnupg
brew install jenv
brew install libyaml
brew install openjdk
brew install maven
brew install mysql
brew install neovim
brew install php
brew install postgresql
brew install source-highlight
brew install terminal-notifier
brew install tmux
brew install zlib

###############################################################################
# Run Homebrew cleanup to remove installation/cached files
###############################################################################
echo "Homebrew: cleaning up..."
brew cleanup


###############################################################################
# Install Node Packages with NPM
###############################################################################
echo "Node: installing Yarn/NPM packages…"
yarn global add http-server
yarn global add prettier
yarn global add netlify-cli


###############################################################################
# Install applications with Homebrew Cask
###############################################################################
echo "Homebrew Cask: installing apps..."
brew install --cask adoptopenjdk9
brew install --cask caret
brew install --cask cyberduck
brew install --cask discord
brew install --cask expressvpn
brew install --cask gitkraken
brew install --cask firefox
brew install --cask google-chrome
brew install --cask docker
brew install --cask github
brew install --cask postman
brew install --cask sourcetree
brew install --cask visual-studio-code
brew install --cask lastpass
brew install --cask alfred
brew install --cask dash
brew install --cask sketch
# brew cask install dropbox
brew install --cask imageoptim
brew install --cask iterm2
brew install --cask notion
brew install --cask obs
brew install --cask slack
brew install --cask spotify
brew install --cask hazel
brew install --cask istat-menus
brew install --cask intellij-idea
brew install --cask webstorm
brew install --cask datagrip
brew install --cask clipy
brew install --cask wifi-explorer
brew install --cask mysqlworkbench
brew install --cask virtualbox



###############################################################################
# Install colorls
###############################################################################
echo "Installing colorls..."
gem install colorls


###############################################################################
# Cleanup
###############################################################################
brew cleanup


###############################################################################
# Install applications with mas-cli (Mac App Store CLI)
###############################################################################
echo "mas-cli: installing Mac App Store apps..."
# Amphetamine
mas install 937984704
# Boop
mas install 1518425043
# ColorSlurp
mas install 1287239339
# Microsoft Remote Desktop
mas install 1295203466
# Session
mas install 1521432881
# The Unarchiver
mas install 425424353
# Todoist
mas install 585829637
# Kindle
mas install 405399194
# Lastpass
mas install 926036361


echo "mas-cli: installing Safar extensions..."
# Hush
mas install 1544743900

###############################################################################
# Install fonts
###############################################################################
echo "Installing Dank Mono..."
cp ~/Dropbox/dot_files/fonts/DankMono/ttf/DankMono-Italic.ttf ~/Library/Fonts
cp ~/Dropbox/dot_files/fonts/DankMono/ttf/DankMono-Regular.ttf ~/Library/Fonts

echo "macOS Config, Dev Tools, Apps are Done Setup!"
echo "Make sure to add /System/Library/Java/... to jEnv with jenv add"
