#!/bin/bash

###############################################################################
# setup-brew
#
# A shell script to automate system tool setup for Mac OS X.
###############################################################################


###############################################################################
# Install Xcode command line tools
###############################################################################
echo "Installing Xcode Command Line Tools..."
xcode-select --install


###############################################################################
# Check for Homebrew, else install
###############################################################################
echo "Checking for, or Installing Homebrew..."
if [ -z `command -v brew` ]; then
    echo "Brew is missing! Installing it..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi;


###############################################################################
# Make sure we're on latest Homebrew
###############################################################################
echo "Homebrew: updating..."
brew update


###############################################################################
# Upgrade any already-installed formulae
###############################################################################
echo "Homebrew: upgrading..."
brew upgrade


###############################################################################
# Install utilities
###############################################################################
echo "Homebrew: updating default unix tools..."
brew install bash
brew install bash-completion
brew install coreutils
brew install findutils
brew install moreutils


###############################################################################
# Install binaries and other packages
###############################################################################
echo "Homebrew: installing binaries and other packages..."
brew install ffmpeg --with-libvpx
brew install git
brew install httpie
brew install imagemagick --with-webp
brew install mackup
brew install mas
brew install nginx
brew install node
brew install nvm
brew install rename
brew install spark
brew install tree
brew install webkit2png
brew install wget --with-iri
brew install yarn


###############################################################################
# Run Homebrew cleanup to remove installation/cached files
###############################################################################
echo "Homebrew: cleaning up..."
brew cleanup


###############################################################################
# Install Node Packages with NPM
###############################################################################
echo "Node: installing Yarn/NPM packages…"
yarn global add @squarespace/server
yarn global add contentful-cli
yarn global add eslint
yarn global add firebase-tools
yarn global add grunt-cli
yarn global add gulp
yarn global add http-server
yarn global add hpm-cli
yarn global add imageoptim-cli
yarn global add js-beautify
yarn global add markdown-pdf
yarn global add netlify-cli
yarn global add newman
yarn global add nodemon
yarn global add now
yarn global add squarespace-cli
yarn global add svgo
yarn global add uglify
yarn global add ultradns-node-cli
yarn global add vue-cli
yarn global add webpack
yarn global add webpack-dev-server
yarn global add wt-cli


###############################################################################
# Install applications with Homebrew Cask
###############################################################################
echo "Homebrew Cask: installing apps..."
brew cask install 1password
brew cask install adobe-creative-cloud
brew cask install alfred
brew cask install box-drive
brew cask install dash
brew cask install docker
# brew cask install dropbox
brew cask install figma
brew cask install firefox
brew cask install framer
brew cask install github-desktop
brew cask install gitter
brew cask install google-cloud-sdk
brew cask install google-chrome
brew cask install google-drive
brew cask install hyper
brew cask install imageoptim
brew cask install iterm2
brew cask install obs
brew cask install paparazzi
brew cask install principle
brew cask install paw
brew cask install postman
brew cask install screaming-frog-seo-spider
brew cask install screenflow
brew cask install sketch
brew cask install sketch-toolbox
brew cask install skype
brew cask install slack
brew cask install spectacle
brew cask install spotify
brew cask install teamviewer
brew cask install toggldesktop
brew cask install tor-browser
brew cask install transmit
brew cask install tunnelbear
brew cask install visual-studio-code
brew cask install whatsapp


###############################################################################
# Execute installers downloaded with Homebrew Cask
###############################################################################
echo "Opening installers..."

echo "Opening Installer: Adobe Creative Cloud"
open /usr/local/Caskroom/adobe-creative-cloud/latest/Creative\ Cloud\ Installer.app/


###############################################################################
# Cleanup
###############################################################################
brew cask cleanup


###############################################################################
# Install applications with mas-cli (Mac App Store CLI)
###############################################################################
echo "mas-cli: installing Mac App Store apps..."
# Amphetamine
mas install 937984704
# BetterSnapTool
mas install 417375580
# DaisyDisk
mas install 411643860
# JPEGmini
mas install 498944723
# Mactracker
mas install 430255202
# Magnet
mas install 441258766
# Sip
mas install 507257563
# Speedtest
mas install 1153157709
# WiFi Explorer
mas install 494803304


echo "macOS Apps Done Setup!"