#!/bin/bash

###############################################################################
# setup-npm
#
# A shell script automate setup of NPM packages.
###############################################################################


###############################################################################
# Install Node Packages with NPM
###############################################################################
echo “Node: installing NPM packages…”
npm i -g @squarespace/server
npm i -g eslint
npm i -g firebase-tools
npm i -g foundation-cli
npm i -g grunt-cli
npm i -g gulp
npm i -g http-server
npm i -g hpm-cli
npm i -g imageoptim-cli
npm i -g netlify-cli
npm i -g newman
npm i -g nodemon
npm i -g npm
npm i -g pageres-cli
npm i -g squarespace-cli
npm i -g svgo
npm i -g uglify
npm i -g ultradns-node-cli
npm i -g vue-cli
npm i -g webpack
npm i -g webpack-dev-server
npm i -g wt-cli