#!/bin/bash

###############################################################################
# setup-npm
#
# A shell script automate setup of NPM packages.
###############################################################################


###############################################################################
# Install Node Packages with NPM
###############################################################################
echo “Node: installing NPM packages…”
npm i -g @squarespace/squarespace-dev-server
npm i -g eslint
npm i -g firebase-tools
npm i -g grunt-cli
npm i -g newman
npm i -g npm
npm i -g pageres-cli
npm i -g svgo
npm i -g uglify
npm i -g vue-cli
npm i -g webpack
npm i -g wt-cli