#!/bin/bash


###############################################################################
# setup-npm
#
# A shell script automate setup of NPM packages.
###############################################################################


###############################################################################
# Install Node Packages with NPM
###############################################################################
echo “Node: installing NPM packages…”
npm install -g eslint
npm install -g firebase-tools
npm install -g grunt-cli
npm install -g node-squarespace-server
npm install -g svgo
npm install -g wt-cli